/root/openstack/logs/2017-02-05/0951/mysqld.log:2017-02-05 09:44:51 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
/root/openstack/logs/2017-02-05/0951/mysqld.log:2017-02-05 09:44:51 11761 [Warning] Buffered warning: Changed limits: max_connections: 214 (requested 500)
/root/openstack/logs/2017-02-05/0951/mysqld.log:2017-02-05 09:44:51 11761 [Warning] Buffered warning: Changed limits: max_open_files: 1024 (requested 5000)
/root/openstack/logs/2017-02-05/0951/mysqld.log:2017-02-05 09:44:51 11761 [Warning] Buffered warning: Changed limits: table_open_cache: 400 (requested 2000)
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:44:51.217 11258 WARNING oslo_db.sqlalchemy.engines [-] SQL connection failed. 10 attempts left.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:44:51.248 11280 WARNING neutron.agent.securitygroups_rpc [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Driver configuration doesn't match with enable_security_group
/root/openstack/logs/2017-02-05/0951/nova-novncproxy.log:2017-02-05 09:44:51.279 11255 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-consoleauth.log:2017-02-05 09:44:52.295 11248 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-api.log:2017-02-05 09:44:52.340 11246 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-conductor.log:2017-02-05 09:44:52.425 11253 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-compute.log:2017-02-05 09:44:52.584 11306 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-scheduler.log:2017-02-05 09:44:52.596 11250 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-05/0951/nova-compute.log:2017-02-05 09:44:52.988 11306 WARNING os_brick.initiator.connectors.remotefs [req-e3ad9fa6-fc18-4a82-a8af-46c937e369b6 - - - - -] Connection details not present. RemoteFsClient may not initialize properly.
/root/openstack/logs/2017-02-05/0951/nova-compute.log:2017-02-05 09:44:54.451 11306 WARNING nova.compute.monitors [req-beecbaf3-e669-4a27-91ac-51d690ef1460 - - - - -] Excluding nova.compute.monitors.cpu monitor virt_driver. Not in the list of enabled monitors (CONF.compute_monitors).
/root/openstack/logs/2017-02-05/0951/nova-compute.log:2017-02-05 09:44:55.070 11306 WARNING nova.scheduler.client.report [req-beecbaf3-e669-4a27-91ac-51d690ef1460 - - - - -] No authentication information found for placement API. Optional use of placement API for reporting is now disabled.
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.492 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension dns-integration not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.500 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension ip_allocation not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.501 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension l2_adjacency not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.507 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension metering not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.517 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension qos not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.521 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension router-service-type not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.524 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension segment not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.530 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension trunk not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.531 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension trunk-details not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:01.532 11258 WARNING neutron.api.extensions [req-1a5e600b-85d6-4c16-9e60-1be366733ee9 - - - - -] Extension vlan-transparent not supported by any of loaded plugins
/root/openstack/logs/2017-02-05/0951/l3-agent.log:2017-02-05 09:45:50.767 11262 ERROR neutron.common.rpc [req-e0004aec-1f08-42ce-8118-321920c462da - - - - -] Timeout in RPC method get_service_plugin_list. Waiting for 37 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-05/0951/l3-agent.log:2017-02-05 09:45:50.771 11262 WARNING neutron.common.rpc [req-e0004aec-1f08-42ce-8118-321920c462da - - - - -] Increasing timeout for get_service_plugin_list calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent 
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent [-] Failed reporting state!
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/metadata/agent.py", line 262, in _report_state
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent MessagingTimeout: Timed out waiting for a reply to message ID 0d04004408d74045b04901398bcfde73
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     retry=retry)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     retry=self.retry)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.781 11260 ERROR neutron.agent.metadata.agent     use_call=self.agent_state.get('start_flag'))
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     ctx, self.agent_state, True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 687, in _report_state
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent MessagingTimeout: Timed out waiting for a reply to message ID 8184b880a46f4bd6b5a28a806ea8eea7
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent [req-f30f4ac2-a335-4300-84bf-a17f8606fe22 - - - - -] Failed reporting state!
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     retry=retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     retry=self.retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.782 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.789 11259 WARNING oslo.service.loopingcall [req-f30f4ac2-a335-4300-84bf-a17f8606fe22 - - - - -] Function 'neutron.agent.dhcp.agent.DhcpAgentWithStateReport._report_state' run outlasted interval by 30.09 sec
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.790 11259 ERROR neutron.common.rpc [req-fa6fdd12-e30f-4b71-8090-678f864c6930 - - - - -] Timeout in RPC method get_active_networks_info. Waiting for 33 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:45:50.791 11259 WARNING neutron.common.rpc [req-fa6fdd12-e30f-4b71-8090-678f864c6930 - - - - -] Increasing timeout for get_active_networks_info calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-05/0951/metadata-agent.log:2017-02-05 09:45:50.792 11260 WARNING oslo.service.loopingcall [-] Function 'neutron.agent.metadata.agent.UnixDomainMetadataProxy._report_state' run outlasted interval by 30.05 sec
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent 
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent [-] Failed reporting state!
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/openvswitch/agent/ovs_neutron_agent.py", line 320, in _report_state
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent MessagingTimeout: Timed out waiting for a reply to message ID f3b7fe0e20054f2b90c8cc5386c8de0a
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     retry=retry)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     retry=self.retry)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.318 11280 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     True)
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.322 11280 WARNING oslo.service.loopingcall [-] Function 'neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent.OVSNeutronAgent._report_state' run outlasted interval by 30.06 sec
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.838 11280 ERROR neutron.common.rpc [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Timeout in RPC method tunnel_sync. Waiting for 14 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:45:51.839 11280 WARNING neutron.common.rpc [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Increasing timeout for tunnel_sync calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:45:56.747 12135 WARNING neutron.db.agents_db [req-ca3985ce-8405-494a-8af3-774a204c69a4 - - - - -] Agent healthcheck: found 1 dead agents out of 4:
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:46:06.885 11280 WARNING neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] ofport: -1 for VIF: 2582bb1a-4fb8-4825-a16a-ad6ad28997bd is not a positive integer
/root/openstack/logs/2017-02-05/0951/server.log:2017-02-05 09:46:08.209 12133 WARNING neutron.plugins.ml2.drivers.type_tunnel [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Endpoint with ip 10.1.1.99 already exists
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:46:08.383 11280 WARNING neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Found failed openvswitch port: tap2582bb1a-4f
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     active_networks = self.plugin_rpc.get_active_networks_info()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 159, in sync_state
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 522, in get_active_networks_info
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 138, in call
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 157, in call
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     host=self.host)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent MessagingTimeout: Timed out waiting for a reply to message ID bca624e3864e4dd58d4da5c233bae3d9
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent [req-fa6fdd12-e30f-4b71-8090-678f864c6930 - - - - -] Unable to sync network state.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     retry=retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     retry=self.retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     return self._original_context.call(ctxt, method, **kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     self.force_reraise()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     six.reraise(self.type_, self.value, self.tb)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     time.sleep(wait)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:23.779 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:46:24.323 11259 WARNING oslo.service.loopingcall [req-b75d8573-149f-4f13-b79a-0cd7f89534a8 - - - - -] Function 'neutron.agent.dhcp.agent.DhcpAgentWithStateReport._report_state' run outlasted interval by 3.53 sec
/root/openstack/logs/2017-02-05/0951/l3-agent.log:2017-02-05 09:46:28.092 11262 WARNING neutron.agent.l3.agent [req-e0004aec-1f08-42ce-8118-321920c462da - - - - -] l3-agent cannot contact neutron server to retrieve service plugins enabled. Check connectivity to neutron server. Retrying... Detailed message: Timed out waiting for a reply to message ID 16ef6a4ca6ff41128683c1f513369e59.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.420 11280 ERROR neutron.agent.linux.utils [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Exit code: 1; Stdin: table=0,in_port=-1,arp; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.422 11280 ERROR neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Unable to execute ['ovs-ofctl', 'del-flows', 'br-int', '-']. Exception: Exit code: 1; Stdin: table=0,in_port=-1,arp; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.429 11280 ERROR neutron.agent.linux.utils [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Exit code: 1; Stdin: table=0,nw_proto=58,icmp_type=136,in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.430 11280 ERROR neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Unable to execute ['ovs-ofctl', 'del-flows', 'br-int', '-']. Exception: Exit code: 1; Stdin: table=0,nw_proto=58,icmp_type=136,in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.439 11280 ERROR neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Unable to execute ['ovs-ofctl', 'del-flows', 'br-int', '-']. Exception: Exit code: 1; Stdin: table=24,in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.439 11280 ERROR neutron.agent.linux.utils [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Exit code: 1; Stdin: table=24,in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.449 11280 ERROR neutron.agent.linux.utils [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Exit code: 1; Stdin: in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:49:54.450 11280 ERROR neutron.agent.common.ovs_lib [req-d3cb2afc-0970-433a-91f9-6b059dafbc39 - - - - -] Unable to execute ['ovs-ofctl', 'del-flows', 'br-int', '-']. Exception: Exit code: 1; Stdin: in_port=-1; Stdout: ; Stderr: 2017-02-05T09:49:54Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.838 11259 ERROR neutron.agent.linux.utils [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Device "tapabd6765f-3e" does not exist.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Device "tapabd6765f-3e" does not exist.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:54.839 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.091 11259 ERROR neutron.agent.linux.utils [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Device "tapabd6765f-3e" does not exist.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Device "tapabd6765f-3e" does not exist.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.092 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.528 11259 ERROR neutron.agent.linux.utils [req-07b49d02-620e-48cb-bc47-af6e104b90b6 - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent [req-07b49d02-620e-48cb-bc47-af6e104b90b6 - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.529 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.631 11259 ERROR neutron.agent.linux.utils [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent [req-b243e6d1-c7fa-449f-abb1-ff4382280408 - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.632 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent [req-799e0575-9ea8-4841-b2f6-07f452cb445d - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:55.975 11259 ERROR neutron.agent.linux.utils [req-799e0575-9ea8-4841-b2f6-07f452cb445d - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.291 11259 ERROR neutron.agent.linux.utils [req-1b0b1bfc-ee92-432f-9693-4653e4569685 - - - - -] Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 114, in call_driver
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 437, in _spawn_or_reload_process
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 481, in _output_config_files
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 500, in reload_allocations
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 851, in _output_opts_file
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 862, in _generate_opts_per_subnet
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py", line 995, in _make_subnet_interface_ip_map
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 105, in _execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 380, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 631, in get_devices_with_ip
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 663, in list
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 81, in _run
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/ip_lib.py", line 96, in _as_root
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py", line 144, in execute
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     for addr in ip_dev.addr.list():
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     for line in self._run(options, tuple(args)).split('\n'):
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     log_fail_as_error=self.log_fail_as_error)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     options, subnet_index_map = self._generate_opts_per_subnet()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent ProcessExecutionError: Exit code: 1; Stdin: ; Stdout: ; Stderr: Cannot open network namespace "qdhcp-99890d45-5e0b-4520-9093-2c0501e6fd24": No such file or directory
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     raise ProcessExecutionError(msg, returncode=returncode)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent [req-1b0b1bfc-ee92-432f-9693-4653e4569685 - - - - -] Unable to reload_allocations dhcp for 99890d45-5e0b-4520-9093-2c0501e6fd24.
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     return self._as_root(options, command, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     return self._parent._run(options, self.COMMAND, args)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     self.name, scope, to, filters, ip_version)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     self._output_config_files()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     self._output_opts_file()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     self._spawn_or_reload_process(reload_with_HUP=True)
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent     subnet_to_interface_ip = self._make_subnet_interface_ip_map()
/root/openstack/logs/2017-02-05/0951/dhcp-agent.log:2017-02-05 09:49:56.292 11259 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:51:24.429 11280 ERROR neutron.agent.linux.async_process [-] Error received from [ovsdb-client monitor Interface name,ofport,external_ids --format=json]: None
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:51:24.430 11280 ERROR neutron.agent.linux.async_process [-] Process [ovsdb-client monitor Interface name,ofport,external_ids --format=json] dies due to the error: None
/root/openstack/logs/2017-02-05/0951/openvswitch-agent.log:2017-02-05 09:51:25.995 13628 WARNING neutron.agent.securitygroups_rpc [req-022dad82-36d5-4693-b408-57d6a582e278 - - - - -] Driver configuration doesn't match with enable_security_group
